-- 테이블 생성
--[ TBL_FOOD_CATEGORY ]
CREATE TABLE TBL_FOOD_CATEGORY(
    CATEGORY_CODE NUMBER CONSTRAINT PK_CATEGORY_CODE PRIMARY KEY
,   CATEGORY VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN TBL_FOOD_CATEGORY.CATEGORY_CODE IS '식품 종류 코드';
COMMENT ON COLUMN TBL_FOOD_CATEGORY.CATEGORY IS '종류명';

--[ TBL_SUPPLIER ]
CREATE TABLE TBL_SUPPLIER(
    CATEGORY_CODE NUMBER
,   SUPPLIER_CODE VARCHAR2(10) 
,   SUPPLIER_NAME VARCHAR2(30) UNIQUE
,   ADDRESS VARCHAR2(80)
,   CONTACT_NUMBER VARCHAR2(20) NOT NULL
,   ORDER_YN VARCHAR2(10) DEFAULT 'Y' CHECK (ORDER_YN IN('Y', 'N')) 
,   CONSTRAINT FK_CATEGORY_CODE FOREIGN KEY(CATEGORY_CODE) REFERENCES TBL_FOOD_CATEGORY(CATEGORY_CODE)
,   CONSTRAINT PK_SUPPLIER_CODE PRIMARY KEY(SUPPLIER_CODE)
);

COMMENT ON COLUMN TBL_SUPPLIER.CATEGORY_CODE IS '식품 종류 코드';
COMMENT ON COLUMN TBL_SUPPLIER.SUPPLIER_CODE IS '업체 코드';
COMMENT ON COLUMN TBL_SUPPLIER.SUPPLIER_NAME IS '업체명';
COMMENT ON COLUMN TBL_SUPPLIER.ADDRESS IS '주소';
COMMENT ON COLUMN TBL_SUPPLIER.CONTACT_NUMBER IS '연락처';
COMMENT ON COLUMN TBL_SUPPLIER.ORDER_YN IS '거래 가능 여부';

--[ TBL_PRODUCTS ]
CREATE TABLE TBL_PRODUCTS(
    PROD_CODE NUMBER
,   PROD_NAME VARCHAR2(30) NOT NULL
,   PRICE NUMBER
,   SUPPLIER_NAME VARCHAR2(30) NOT NULL
,   CONSTRAINT PK_PROD_CODE PRIMARY KEY(PROD_CODE)
);

COMMENT ON COLUMN TBL_PRODUCTS.PROD_CODE IS '재료 코드';
COMMENT ON COLUMN TBL_PRODUCTS.PROD_NAME IS '재료명';
COMMENT ON COLUMN TBL_PRODUCTS.PRICE IS '재료가격';
COMMENT ON COLUMN TBL_PRODUCTS.SUPPLIER_NAME IS '업체명';

--[ TBL_STORAGE ]
CREATE TABLE TBL_STORAGE(
    PROD_CODE NUMBER NOT NULL
,   PROD_NAME VARCHAR2(30) NOT NULL
,   INCOMING_DATE VARCHAR2(10) NOT NULL
);

COMMENT ON COLUMN TBL_STORAGE.PROD_CODE IS '재료 코드';
COMMENT ON COLUMN TBL_STORAGE.PROD_NAME IS '재료명';
COMMENT ON COLUMN TBL_STORAGE.INCOMING_DATE IS '입고날짜';

--[ TBL_ORDER_HISTORY ]
CREATE TABLE TBL_ORDER_HISTORY(
    ORDER_CODE NUMBER
,   ORDER_DATE VARCHAR2(10) NOT NULL
,   ORDER_TIME VARCHAR2(10)
,   TOTAL_PRICE NUMBER NOT NULL
,   CONSTRAINT PK_ORDER_CODE PRIMARY KEY(ORDER_CODE)
);

COMMENT ON COLUMN TBL_ORDER_HISTORY.ORDER_CODE IS '주문코드';
COMMENT ON COLUMN TBL_ORDER_HISTORY.ORDER_DATE IS '주문일자';
COMMENT ON COLUMN TBL_ORDER_HISTORY.ORDER_TIME IS '주문시각';
COMMENT ON COLUMN TBL_ORDER_HISTORY.TOTAL_PRICE IS '주문총액';

--------------------------------------------------------------------------------
--시퀀스 생성
--[ CATEGORY_CODE ]
CREATE SEQUENCE SEQ_CATEGORY_CODE
START WITH 1
INCREMENT BY 1
MAXVALUE 10
NOCYCLE
NOCACHE;
--[ PROD_CODE ]
CREATE SEQUENCE SEQ_PROD_CODE
START WITH 100
INCREMENT BY 1
MAXVALUE 999
NOCYCLE
NOCACHE;
--[ ORDER_CODE ]
CREATE SEQUENCE SEQ_ORDER_CODE
START WITH 1000
INCREMENT BY 1
MAXVALUE 9999
NOCYCLE
NOCACHE;

--------------------------------------------------------------------------------
--컬럼 값 삽입
--[ TBL_FOOD_CATEGORY ]
INSERT INTO TBL_FOOD_CATEGORY VALUES(SEQ_CATEGORY_CODE.NEXTVAL, '육류');
INSERT INTO TBL_FOOD_CATEGORY VALUES(SEQ_CATEGORY_CODE.NEXTVAL, '어류');
INSERT INTO TBL_FOOD_CATEGORY VALUES(SEQ_CATEGORY_CODE.NEXTVAL, '과일,채소류');
INSERT INTO TBL_FOOD_CATEGORY VALUES(SEQ_CATEGORY_CODE.NEXTVAL, '유제품');
INSERT INTO TBL_FOOD_CATEGORY VALUES(SEQ_CATEGORY_CODE.NEXTVAL, '냉동식품');
INSERT INTO TBL_FOOD_CATEGORY VALUES(SEQ_CATEGORY_CODE.NEXTVAL, '건조식품');
INSERT INTO TBL_FOOD_CATEGORY VALUES(SEQ_CATEGORY_CODE.NEXTVAL, '기타');

--[ TBL_SUPPLIER ]
INSERT INTO TBL_SUPPLIER VALUES(1, '1A', '굽네정육', '서울시 성동구 마장동 고깃길 79',	'02-6549-2341', DEFAULT);
INSERT INTO TBL_SUPPLIER VALUES(2, '2A', '바다회사랑', '서울시 동작구 노량진수산물도매시장 7-A', '02-4061-0605', DEFAULT);
INSERT INTO TBL_SUPPLIER VALUES(3, '3A', 'SING싱채소'	, '서울시 동대문구 제기동 청량리청과물시장 185호', '070-3059-4953', DEFAULT);
INSERT INTO TBL_SUPPLIER VALUES(3, '3B', '베지상회', '경기도 남양주시 야채로2길 71', '031-3421-5800', DEFAULT);
INSERT INTO TBL_SUPPLIER VALUES(4, '4A', '치즈FARM', '경기도 파주시 우유리 921-12', '031-9372-0221', DEFAULT);
INSERT INTO TBL_SUPPLIER VALUES(5, '5A', '얼음땡푸드', '서울시 종로구 꽁꽁3가 2-38', '02-5068-4480', DEFAULT);
INSERT INTO TBL_SUPPLIER VALUES(6, '6A', '짱구는말려', '경기도 하남시 흰둥로 600', '070-3242-1666', DEFAULT);
INSERT INTO TBL_SUPPLIER VALUES(7, '7A', '꼬순내방앗간', '경기도 이천시 무촌리 52-7', '031-2221-5838', DEFAULT);
INSERT INTO TBL_SUPPLIER VALUES(7, '7B', 'EGG머니나',	 '서울시 도봉구 병아리길 92', '02-7483-8812', DEFAULT);

--[ TBL_PRODUCTS ]
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '소 등심', 20000,	'굽네정육');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '소 안심', 23000,	'굽네정육');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '소 다짐육', 15000, '굽네정육');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '돼지 등심', 10000, '굽네정육');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '돼지 안심', 15000, '굽네정육');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '돼지 다짐육',	8000, '굽네정육');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '닭 안심',	 7000, '굽네정육');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '연어', 20000, '바다회사랑');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '새우', 11000, '바다회사랑');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '오징어',	5000, '바다회사랑');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '가자미',	10000, '바다회사랑');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '바지락',	5000, '바다회사랑');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '모시조개', 6000, '바다회사랑');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '당근', 3000,	'SING싱채소');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '양파', 4000,	'SING싱채소');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '샐러리',	3000, 'SING싱채소');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '양배추',	6000, 'SING싱채소');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '비트', 3000,	'SING싱채소');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '감자', 4000,	'SING싱채소');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '고구마',	4000, 'SING싱채소');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '호박', 8000,	'SING싱채소');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '딸기', 7000,	'SING싱채소');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '바나나',	4000, 'SING싱채소');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '키위', 8000,	'SING싱채소');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '로즈마리', 7000, '베지상회');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '쪽파', 4000,	'베지상회');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '깻잎', 2000,	'베지상회');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '무순', 4000,	'베지상회');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '양송이버섯', 5000, '베지상회');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '딜',	 7000, '베지상회');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '우유', 4000, '치즈FARM');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '생크림',	7000, '치즈FARM');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '체다치즈', 5000, '치즈FARM');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '크림치즈', 7000, '치즈FARM');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '리코타치즈', 9000, '치즈FARM');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '냉동감자튀김',	 10000,	'얼음땡푸드');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '냉동고구마튀김', 12000, '얼음땡푸드');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '냉동만두', 7000, '얼음땡푸드');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '냉동블루베리', 15000, '얼음땡푸드');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '호박씨',	5000, '짱구는말려');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '해바라기씨', 4000, '짱구는말려');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '건포도',	4000, '짱구는말려');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '건크랜베리', 6000, '짱구는말려');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '곰표밀가루', 6000, '꼬순내방앗간');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '쌀가루',	8000, '꼬순내방앗간');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '빵가루',	4000, '꼬순내방앗간');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '콩가루',	3000, '꼬순내방앗간');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '유기농 달걀',	10000, 'EGG머니나');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '하얀 달걀', 8000,	'EGG머니나');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '특대 달걀', 7000,	'EGG머니나');
INSERT INTO TBL_PRODUCTS VALUES(SEQ_PROD_CODE.NEXTVAL, '일반 달걀', 5000,	'EGG머니나');

--[ TBL_STORAGE ]
INSERT INTO TBL_STORAGE VALUES(101, '소 안심', SYSDATE);
INSERT INTO TBL_STORAGE VALUES(105, '돼지 다짐육', SYSDATE);
INSERT INTO TBL_STORAGE VALUES(108, '새우', SYSDATE);
INSERT INTO TBL_STORAGE VALUES(112, '모시조개', SYSDATE);
INSERT INTO TBL_STORAGE VALUES(116, '양배추', SYSDATE);
INSERT INTO TBL_STORAGE VALUES(122, '바나나', SYSDATE);
INSERT INTO TBL_STORAGE VALUES(131, '생크림', SYSDATE);
INSERT INTO TBL_STORAGE VALUES(138, '냉동블루베리', SYSDATE);
INSERT INTO TBL_STORAGE VALUES(143, '밀가루', SYSDATE);
INSERT INTO TBL_STORAGE VALUES(147, '유기농 달걀', SYSDATE);

COMMIT;
